on:
  [push, pull_request]

name: Tests

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Install
      run: |
        npm ci
    - name: Test
      run: |
        npm t
